DROP TABLE AUDIT_LOG CASCADE CONSTRAINTS;
DROP TABLE AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE BATCH_RUN CASCADE CONSTRAINTS;
DROP TABLE BATCH_RUN_SIMULATION_RUN CASCADE CONSTRAINTS;
DROP TABLE COLLECTOR_INFORMATION CASCADE CONSTRAINTS;
DROP TABLE COLLECTOR_MAPPING CASCADE CONSTRAINTS;
DROP TABLE COMMENT_TAG CASCADE CONSTRAINTS;
DROP TABLE CONFIG_OBJECT_HOLDER CASCADE CONSTRAINTS;
DROP TABLE DAO_PARAMS CASCADE CONSTRAINTS;
DROP TABLE DATE_TYPE_TEST CASCADE CONSTRAINTS;
DROP TABLE DISTRIBUTION CASCADE CONSTRAINTS;
DROP TABLE FIELD_MAPPING CASCADE CONSTRAINTS;
DROP TABLE GLOBAL_DATES CASCADE CONSTRAINTS;
DROP TABLE MDP_TITLE CASCADE CONSTRAINTS;
DROP TABLE MDP_VALUE CASCADE CONSTRAINTS;
DROP TABLE MODELDAO CASCADE CONSTRAINTS;
DROP TABLE PARAMETER CASCADE CONSTRAINTS;
DROP TABLE PARAMETER_ENTRY CASCADE CONSTRAINTS;
DROP TABLE PARAMETERIZATION_TAG CASCADE CONSTRAINTS;
DROP TABLE PARAMETERIZATIONDAO CASCADE CONSTRAINTS;
DROP TABLE PATH_MAPPING CASCADE CONSTRAINTS;
DROP TABLE PERSON CASCADE CONSTRAINTS;
DROP TABLE PERSON_AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE POST_SIMULATION_CALCULATION CASCADE CONSTRAINTS;
DROP TABLE RESULT_CONFIGURATIONDAO CASCADE CONSTRAINTS;
DROP TABLE RESULT_STRUCTUREDAO CASCADE CONSTRAINTS;
DROP TABLE SIMULATION_RUN CASCADE CONSTRAINTS;
DROP TABLE STRUCTURE_MAPPING CASCADE CONSTRAINTS;
DROP TABLE SYMBOLIC_VALUE_RESULT CASCADE CONSTRAINTS;
DROP TABLE SYSTEMATIC_EVENT_PARAMETERS CASCADE CONSTRAINTS;
DROP TABLE TAG CASCADE CONSTRAINTS;
DROP TABLE USER_SETTINGS CASCADE CONSTRAINTS;
DROP TABLE WORKFLOW_COMMENTDAO CASCADE CONSTRAINTS;
DROP TABLE DAO_PARAMETER CASCADE CONSTRAINTS;
DROP TABLE DATE_DATATYPE_TEST CASCADE CONSTRAINTS;
DROP TABLE SINGLE_VALUE_RESULT CASCADE CONSTRAINTS;
DROP TABLE COMMENTDAO CASCADE CONSTRAINTS;
DROP TABLE MODEL_STRUCTUREDAO CASCADE CONSTRAINTS;
DROP TABLE RUN_PARAMETER CASCADE CONSTRAINTS;

DROP SEQUENCE result_id_sequence;

CREATE SEQUENCE result_id_sequence
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE TABLE single_value_result (
id NUMBER(19) NOT NULL,
version NUMBER(19) NOT NULL,
iteration int NOT NULL,
path_id NUMBER(19) NOT NULL,
collector_id NUMBER(19) NOT NULL,
value_index int NOT NULL,
field_id NUMBER(19) NOT NULL,
period int NOT NULL,
simulation_run_id NUMBER(19) NOT NULL,
value FLOAT(126) NOT NULL,
date_time NUMBER(19) DEFAULT NULL
);

--TODO: path/field tables, indices, view, tablespace, partitions